spring.application.name=auth

spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=theo
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

app.secret-key=${JWT_SECRET}
app.expiration-time=900000
